nginx:
  image: nginx:stable-alpine
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./:/home/www/public_html/registree.rocks/public/
    - ./nginx:/etc/nginx/
    - ~/cert:/etc/cert
  # restart: always